### ISSUE TITLE
Error in mitmlComplete() with single missing value in categorical variables

### ISSUE THREAD

**Issue by simongrund1** [simongrund1/mitml#1]
When there is only a single missing value in a categorical variable, `mitmlComplete()` gives the following error:

```
Error in `[<-.data.frame`(`*tmp*`, ind[fi, ], value = "1") :
 new columns would leave holes after existing columns
```

**Comment by sakuramomo1005** [comment]
Dear simongrund1, I meet the same problem. How did you fix it? Thank you so much!!
