### ISSUE TITLE
mitml package

### ISSUE THREAD

**Issue by SarahElgerby** [simongrund1/mitml#23]
I already installed the package but I keep on having this message "could not find function "mitml" how can i fix that

**Comment by simongrund1** [comment]
There is no function called `mitml()` in the `mitml` package, so just calling `mitml()` will cause this message. For a short introduction on how to use this package, plese see this vignette: [https://cran.r-project.org/web/packages/mitml/vignettes/Introduction.html](https://cran.r-project.org/web/packages/mitml/vignettes/Introduction.html). Please also see the documentation for a list of available commands: [https://cran.r-project.org/web/packages/mitml/mitml.pdf](https://cran.r-project.org/web/packages/mitml/mitml.pdf).
