### ISSUE TITLE
Error in if(ll_change < conv_dev)

### ISSUE THREAD

**Issue by craigenders** [simongrund1/mitml#25]
Hello Simon,
I hope you are doing well. I am putting together some training materials for the department of ed. One of my mitml examples no longer runs and gives the following error.

<img width="647" alt="Screenshot 2024-08-29 at 9 00 38 AM" src="https://github.com/user-attachments/assets/dafed6d0-241b-400d-8f42-5ac668abfd05">

I am attaching the data and script for your review.

Best,
Craig Enders

[mitml error.zip](https://github.com/user-attachments/files/16801937/mitml.error.zip)

**Comment by simongrund1** [comment]
Hi, Craig! Thanks for reporting. The issue seems to be related to `mdmb` and not `mitml`, correct? If so, could you please file this report at the `mdmb` repo ([https://github.com/alexanderrobitzsch/mdmb](https://github.com/alexanderrobitzsch/mdmb))?

**Comment by simongrund1** [comment]
Closing this for now due to lack of activity, but please let me know if it should be reopened.

**Comment by craigenders** [comment]
Hi Simon,
I’m so sorry, I feel stupid. I had both of your githubs open side by side to see if I had the most recent updates, and I accidentally swapped my report. So sorry to waste your time. But while I have you, thanks for all your great work on the software, I couldn’t do my work without it.
Best,
Craig

From: Simon Grund ***@***.***>
Date: Friday, August 30, 2024 at 4:49 AM
To: simongrund1/mitml ***@***.***>
Cc: Enders, Craig ***@***.***>, Author ***@***.***>
Subject: Re: [simongrund1/mitml] Error in if(ll_change < conv_dev) (Issue #25)

Hi, Craig! Thanks for reporting. The issue seems to be related to mdmb and not mitml, correct? If so, could you please file this report at the mdmb repo (https://github.com/alexanderrobitzsch/mdmb)?

**Comment by simongrund1** [comment]
No worries, and thanks for the kind words. Glad you find the package useful!
