### ISSUE TITLE
Error in testModels (Error in solve.default(Ubar) : 'a' is 0-diml)

### ISSUE THREAD

**Issue by laetulos** [simongrund1/mitml#4]
First, thanks so much for your work on mitml!  I've been waiting for someone to make pan usable for a long time and to implement multiple df tests for MI. 

Unfortunately, I'm getting an error with testEstimates, R output is below. Any thoughts would be greatly appreciated!  Thanks, Lee

```r
imp.test <- with(implist, lmer(cbcl_ext_raw ~ Time +(1 + Time|ChildID), REML=F))
imp.g2.ext <- with(implist, lmer(cbcl_ext_raw ~ Time + female + Time:female + (1 + Time|ChildID), REML=F))

testEstimates(imp.test , var.comp=TRUE)

Call:

testEstimates(model = imp.test, var.comp = TRUE)

Final parameter estimates and inferences obtained from 20 imputed data sets.

             Estimate Std.Error   t.value        df   P(>|t|)       RIV       FMI 
(Intercept)     8.808     0.448    19.664   117.838     0.000     0.671     0.411 
Time           -0.123     0.041    -2.983    65.741     0.004     1.163     0.551 

                             Estimate 
Intercept~~Intercept|ChildID   25.031 
Intercept~~Time|ChildID        -0.178 
Time~~Time|ChildID              0.063 
Residual~~Residual             27.086 
ICC|ChildID                     0.480 

Unadjusted hypothesis test as appropriate in larger samples. 

testEstimates(imp.g2.ext , var.comp=TRUE)

Call:

testEstimates(model = imp.g2.ext, var.comp = TRUE)

Final parameter estimates and inferences obtained from 20 imputed data sets.

             Estimate Std.Error   t.value        df   P(>|t|)       RIV       FMI 
(Intercept)     9.206     0.544    16.919   133.098     0.000     0.607     0.387 
Time           -0.147     0.053    -2.782    75.783     0.007     1.003     0.513 
female         -0.828     0.645    -1.284   182.498     0.201     0.476     0.330 
Time:female     0.051     0.068     0.755   104.853     0.452     0.741     0.436 

                             Estimate 
Intercept~~Intercept|ChildID   24.591 
Intercept~~Time|ChildID        -0.156 
Time~~Time|ChildID              0.062 
Residual~~Residual             27.073 
ICC|ChildID                     0.476 

Unadjusted hypothesis test as appropriate in larger samples. 

testModels (imp.test,imp.g2.ext)
Error in solve.default(Ubar) : 'a' is 0-diml
```

**Comment by simongrund1** [comment]
Thanks for bringing this up. The error seems to come from `testModels` rather than `testEstimates`, so I changed the title of the issue. I also reformatted your code so that it's readable. Hope that's okay!

The error occurs because `testModels` expects the more general model as its first argument and the restricted model as the second. The correct call would be:

```{r}
testModels(imp.g2.ext, imp.test)
```

which should give the desired results. You can also make that explicit by using the functions named arguments, in which case R allows for the arguments to be supplied in an arbitrary order, so both of the following should work as well:

```{r}
testModels(model=imp.g2.ext, null.model=imp.test)
testModels(null.model=imp.test, model=imp.g2.ext)
```

Does this solve the problem?

**Comment by laetulos** [comment]
Thank you Simon, it works fine now. It always needs to be something stupid like that, in any case, now it is in the record so that other folks who make the same mistake can first try switching the order of their arguments. Again, your work on this is greatly appreciated, until now I've generally advised my students to avoid multilevel imputation as the amount of pain was just too high, mitml changes that equation and makes this much more accessible. Best, Lee
